services:
  js:
    build: .
    container_name: js-dev
    volumes:
      - ./workspace:/workspace
    ports:
      - "5500:5500" # live-server デフォルトポート
    working_dir: /workspace
    tty: true
    command: live-server --host=0.0.0.0 --port=5500
